server:
  port: 8081

spring:
  application:
    name: user-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ticketdb}
    username: ${SPRING_DATASOURCE_USERNAME:naingseiha}
    password: ${SPRING_DATASOURCE_PASSWORD:#Iamaprogrammer@1}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true
    defer-data-source-initialization: true